### ISSUE TITLE
[BUG] QS Panel Color not fully applied

### ISSUE THREAD

**Issue by efirium2018** [BlissRoms/bug_reports#28]
**Color qs panel is not fully applied**
 
I don’t see the point in a step-by-step explanation of how to detect this and what will happen, since the bug is not super critical.  Therefore, I will briefly explain, I will attach a screenshot and video.

when changing the color of the qs panel, it is not fully applied in some elements, I don’t know if this is the bug or it should be, but it looks awful, and I would like the color to be completely changed

**Screenshots**

![Screenshot_20200531-010440028 (1)](https://user-images.githubusercontent.com/48407418/83340153-6b4e7f00-a2dd-11ea-8bea-ab0c92ebbd5a.jpg)

https://streamable.com/ex0dks

**Device:**
santoni

**Comment by rohanpurohit** [comment]
yes you are right ! but unfortunately that is not possible , as they are supposed to change with primary themes(color) in blissify> themes. this feature was added just to change the panel background and not entire system wide, that is again governed by primary, this feature was added because when u disable "use default colors" user needs to have control to use what he wants, as u can see in the screenshot, those are wallpaper, accent color and panel color !
