### ISSUE TITLE
[BUG] <!-- Add your summary of the bug faced here -->

### ISSUE THREAD

**Issue by leosid-dev** [BlissRoms/bug_reports#89]
### Issue type

User interface

### Device

miatoll

### Bliss build

Bliss-v17.8.1-miatoll-OFFICIAL-vanilla-20241014

### Bug Description

Blur not working as intended when enabled(Allow Window level blur) in recents

### Steps to reproduce

change ro.sf.blurs_are_expensive=1
ro.surface_flinger.supports_background_blur=1 in build.prop

### Expected Behavior

blur in recents should be working as intended

### Current Behavior

frame drops in recents and becomes laggy

### Relevant log (logcat/build log)

```shell
recents with unstable frames...you get it.
```

### Possible Solution

might be a surface flinger issue

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by UknowEtheG** [comment]
Since you made it clear you were modifying system files...

Can you please provide any details regarding what other modifications or customizations you have made since flashing the build as it was shipped. 

Anytime you'd like to share a log we'd love to get it

**Comment by StudioKeys** [comment]
Hello,

For context, the mentioned device (i.e., miatoll-family devices) aren't those which has high end SOCs so that changing blurs would fix as at the end of day, whatever change you do to the software lying above needs to correspond with the bare metal HW. 
At the moment, you are trying to go overboard the limit which the device cant handle and the maintainer is aware of it, for which why the blurs are set to minimal or off.

Pls. Understand that HW cant be upgraded with every software change plus the bundled props had no issues unless u change them, so for usable cases just use whats offered as those are tested for stability and functionality.

Cheers,
StudioKeys
